# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
# url: http://localhost:3000
# baseurl: ""
url: https://lengocluyen.github.io
baseurl: ""
title: Le Ngoc Luyen's Personal Site
author: Ngoc Luyen Le
description: Personal blog and resume
avatar: profile.jpg
photoavatar: photocuzco.jpg
photoavatar1: photo2.jpg
photoavatar2: photo3.jpg
email: luyenlengoc@gmail.com
cvfullen: 04_cv_main_en.pdf
cvfullfr: 04_cv_main.pdf
github: lengocluyen # username
hal: luyen-le-ngoc
researchgate: le-luyen
orcid: 0000-0002-2043-0679
twitter: lengocluyen
linkedin: lengocluyen
googlescholar: tFnk5VIAAAAJ
stackoverflow: users/7595772/le-ngoc-luyen   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1
google_maps: https://www.google.com/maps/place/13+Rue+Winston+Churchill,+60200+Compi%C3%A8gne/@49.4106871,2.8128797,17z/data=!3m1!4b1!4m6!3m5!1s0x47e7d42710caccc1:0xf38b75e779ba1187!8m2!3d49.4106871!4d2.8128797!16s%2Fg%2F11c0z4jzyq?entry=ttu
tel: +33 7 83 75 95 10
tel_full: tel:+33 7 83 75 95 10
website: lengocluyen.github.io
website_full: https://lengocluyen.github.io
address:
  street: 13 Rue Winston Churchill
  postcode: 60200
  city: Compi√®gne
  country: France

# needed for travis-ci build
exclude: [vendor]
